### ISSUE TITLE
etana produces JSON that crashes etdisamb

### ISSUE THREAD

**Issue by Kaljurand** [Filosoft/vabamorf#18]
"etdisamb" crashes with error:

    JSON error: Missing ',' in map

on this commandline:

    cat test.json | ./etana analyze -lex ~/myapps/vabamorf/dct/binary/et.dct   | ./etdisamb -lex et3.dct

where the content of test.json is:

```
{
  "paragraphs": [
    {
      "sentences": [
        {
          "words": [
            {
              "text": "\""
            }
          ]
        }
      ]
    }
  ]
}
```

it seems that etana overescapes:

    "text": "\\""

**Comment by PRR24** [comment]
Fixed.
