### ISSUE TITLE
Kompileerimine Os X-s (Yosemite 10.10.5). Võimalik lahendus.

### ISSUE THREAD

**Issue by ikiissel** [Filosoft/vabamorf#23]
Kui keegi peaks veel jänni jääma osx-i all kompileerimisega, siis mina sain käima nõnda. Võiks sobida kõigi uuemate osx-dega. (analüüs, ühestaja ja süntees testitud)

1. faili stdfsc.h tuleks lisada näiteks nii

                     #define MAC
                 #endif

                + #if defined (__APPLE__) && !defined (MAC)
                +    #define UNIX
                + #endif

                #if defined (_UNICODE) && !defined (UNICODE)

2. Makefile'ides "FLAGS=" real tuleks "Wl,--gc-sections" asendada "-Wl,-dead_strip"

Väljundis on hulgaliselt _fabs()_ hoiatusi, aga kompileerub.

**Comment by PRR24** [comment]
Ma soovitaks omalt poolt koodi mitte muuta ja kasutada lihtsalt -DUNIX parameetrit kui POSIX mõtteis mõlgub. Seda siis nii Lixux, Mac, Solaris või mõnel teisel *ix platvormil. Teegid ja optimeerimisvõtmed sõltuvad muidugi konkreetsest kompilaatorist ja platvormist.
