### ISSUE TITLE
Morfoanalüüsi JSON väljundis osade reavahatuste asemel \n (kaks tähemärki)

### ISSUE THREAD

**Issue by tpetmanson** [Filosoft/vabamorf#25]
Tere!

Praegune vabamorf annab Linux Mint 17.3 operatsioonisüsteemis väljundi, milles osad reavahetused tunduvad olevat `escapetud`. Logist näen, et JSONi kirjutamisega on hiljuti toimunud muudatusi, seega kahtlustan, et probleem võib olla sellega seoses. Umbes 6+ kuud tagasi väljundis seda viga ei märganud.

`$ ./etana analyze -guess -in test.txt -out test.out.txt`

Sisend ja väljund:
[test.txt](https://github.com/Filosoft/vabamorf/files/125348/test.txt)
[test.out.txt](https://github.com/Filosoft/vabamorf/files/125349/test.out.txt)

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
x86_64-linux-gnu

**Comment by PRR24** [comment]
Fixed.

**Comment by tpetmanson** [comment]
Yes, now it works!
