### ISSUE TITLE
LICENSE clarification

### ISSUE THREAD

**Issue by jaakristioja** [Filosoft/vabamorf#29]
The contents of the [LICENSE](https://github.com/Filosoft/vabamorf/blob/550d2d7e598705adfc469bba2ba4b53d45fbb8c5/LICENSE) file are currently as follows:

```
Copyright (c) 2015, Filosoft

Tarkvara on litsentseeritud LGPL alustel.

Software is licensed under LGPL.
```

Assuming that by `LGPL` the GNU Lesser General Public License is meant, could you please clarify under which exact version of the LGPL the software is licensed? Thanks!

**Comment by PRR24** [comment]
LGPL 3
